# Generated by Django 4.2.11 on 2024-05-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='Ecommerce/static/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='Ecommerce.CartItem', to='Ecommerce.items'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Ecommerce.items'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
